#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

bash -n "${ROOT}/build.sh"
bash -n "${ROOT}/bin/hatch"
bash -n "${ROOT}/lib/common.sh"
bash -n "${ROOT}/scripts/build_wheelhouse.sh"
bash -n "${ROOT}/scripts/build_mona_tools_pack.sh"
bash -n "${ROOT}/scripts/prepare_mona_tools_inputs.sh"
bash -n "${ROOT}/scripts/prepare_skill_deps_inputs.sh"
bash -n "${ROOT}/scripts/build_skill_deps_pack.sh"
bash -n "${ROOT}/scripts/stage_vendor_python_macos.sh"
bash -n "${ROOT}/templates/install.sh"
bash -n "${ROOT}/templates/install-gemma-model.sh"
bash -n "${ROOT}/templates/install-mona-tools.sh"
bash -n "${ROOT}/templates/install-skill-deps.sh"
bash -n "${ROOT}/tests/hatch_dry_run_tests.sh"
bash -n "${ROOT}/tests/hatch_build_tests.sh"
bash -n "${ROOT}/tests/hatch_model_pack_tests.sh"
bash -n "${ROOT}/tests/hatch_mona_tools_pack_tests.sh"
bash -n "${ROOT}/tests/hatch_provisioning_lock_tests.sh"
bash -n "${ROOT}/tests/hatch_provisioning_smoke_tests.sh"
bash -n "${ROOT}/tests/hatch_wheelhouse_tests.sh"
bash -n "${ROOT}/tests/hatch_skill_deps_scaffold_tests.sh"
bash -n "${ROOT}/tests/hatch_skill_readiness_gate_tests.sh"
bash -n "${ROOT}/tests/hatch_bundle_atomicity_tests.sh"
python3 -m py_compile "${ROOT}/scripts/generate_manifest.py"
python3 -m py_compile "${ROOT}/scripts/generate_model_pack_manifest.py"
python3 -m py_compile "${ROOT}/scripts/generate_tools_pack_manifest.py"
python3 -m py_compile "${ROOT}/scripts/mona_tools_ensure_node_runtime.py"
python3 -m py_compile "${ROOT}/scripts/verify_skill_bundle.py"
bash "${ROOT}/tests/hatch_dry_run_tests.sh"
bash "${ROOT}/tests/hatch_build_tests.sh"
bash "${ROOT}/tests/hatch_model_pack_tests.sh"
bash "${ROOT}/tests/hatch_mona_tools_pack_tests.sh"
bash "${ROOT}/tests/hatch_provisioning_lock_tests.sh"
bash "${ROOT}/tests/hatch_provisioning_smoke_tests.sh"
bash "${ROOT}/tests/hatch_wheelhouse_tests.sh"
bash "${ROOT}/tests/hatch_skill_deps_scaffold_tests.sh"
bash "${ROOT}/tests/hatch_skill_readiness_gate_tests.sh"
bash "${ROOT}/tests/hatch_bundle_atomicity_tests.sh"
